spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样疼值介于e到1之间，1则表示全部采集
      probability: 1

# eureka 配置
eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进Eurekaserver群认为true。
    fetchRegistry: true # true衣示自己端成是注册中心，我的积资就是签我服务实，并不需延去检索服务
    # #设置与Eureka Server交互的始址查询服务和注般服务部需要在藏这个婚址
    service-url:
      defaultZone: http://eureka-server:7001/eureka
  instance:
    instance-id: passport-service
    prefer-ip-address: true

# 设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监州哪个接口
    com.sky.cloud.service.OrderFeignService: debug

# feign 配置对hystrix的支持
feign:
  hystrix:
    enabled: true