spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样疼值介于0到1之间，1则表示全部采集
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'