# eureka 配置
eureka:
  client:
    register-with-eureka: true # 表示是否将自己注册进Eurekaserver群认为true。
    fetchRegistry: true # true衣示自己端成是注册中心，我的积资就是签我服务实，并不需延去检索服务
    # #设置与Eureka Server交互的始址查询服务和注般服务部需要在藏这个婚址
    service-url:
      defaultZone: http://eureka-server:7001/eureka
  instance:
    instance-id: gateway-server
    prefer-ip-address: true

# gateway 配置
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #让gateway可以发现nacos或者eureka中的微服务
      routes:
        - id: order-service-route      #路由ID，没有固定规则但要求唯一，建议配合服务名uri:http:/localhost:8000#匹配后提供服务的路由地
          uri: lb://order-service     #lb指的是从nacos或者eureka中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/order/list/**      #断言，路径相匹配的进行路由
        - id: order-service-route2
          uri: lb://order-service
          predicates:
            - Path=/order/info/**
        - id: order-service-route3
          uri: lb://order-service
          predicates:
            - Path=/order/create/**
            #- After=2020-12-23T15:27:57.999+08:00[Asia/Shanghai]
            #- Cookie=username,cuixinfu            #请求头带cookie
            #- AddRequestHeade=X-Request-red, blue #请求头要X-Request-Id属性并互值为整数的正则表达式
            #- PrefixPath=/order                   #请求前缀要为这个
            #- Host=**.sky.com
            #- Method=POST
